<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-01T15:44:38 IST" name="Default suite" finished-at="2025-07-01T15:44:49 IST" duration-ms="10609">
    <groups>
    </groups>
    <test started-at="2025-07-01T15:44:38 IST" name="Default test" finished-at="2025-07-01T15:44:49 IST" duration-ms="10609">
      <class name="api.test.StoreTests2">
        <test-method is-config="true" signature="setup()[pri:0, instance:api.test.StoreTests2@3754a4bf]" started-at="2025-07-01T15:44:38 IST" name="setup" finished-at="2025-07-01T15:44:39 IST" duration-ms="629" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testPostStore()[pri:1, instance:api.test.StoreTests2@3754a4bf]" started-at="2025-07-01T15:44:39 IST" name="testPostStore" finished-at="2025-07-01T15:44:44 IST" duration-ms="5518" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostStore -->
        <test-method signature="testGetOrderByOrderId()[pri:2, instance:api.test.StoreTests2@3754a4bf]" started-at="2025-07-01T15:44:44 IST" name="testGetOrderByOrderId" finished-at="2025-07-01T15:44:46 IST" duration-ms="1456" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at api.test.StoreTests2.testGetOrderByOrderId(StoreTests2.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetOrderByOrderId -->
        <test-method signature="getStoreInventory()[pri:3, instance:api.test.StoreTests2@3754a4bf]" started-at="2025-07-01T15:44:46 IST" name="getStoreInventory" finished-at="2025-07-01T15:44:47 IST" duration-ms="1365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getStoreInventory -->
        <test-method signature="testDeleteOrderByOrderId()[pri:4, instance:api.test.StoreTests2@3754a4bf]" started-at="2025-07-01T15:44:47 IST" name="testDeleteOrderByOrderId" finished-at="2025-07-01T15:44:49 IST" duration-ms="1549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteOrderByOrderId -->
      </class> <!-- api.test.StoreTests2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
